"""Regression coverage for safe ordinary-update EOL handling.

A CRLF-only difference can be generated by Git attributes, but it can also be
an intentional byte-level user edit.  The update boundary therefore treats
EOL state like every other local change: the compatibility hook is an exact
no-op, the ordinary update autostash captures dirty bytes, and the restore
path puts those bytes back exactly once.
"""

from __future__ import annotations

import shutil
import subprocess
from pathlib import Path
from types import SimpleNamespace

import pytest

from hermes_cli import main as hermes_main
from hermes_cli import update_cmd

pytestmark = pytest.mark.skipif(shutil.which("git") is None, reason="needs git")

GIT_CMD = ["git"]


def _git(cwd: Path, *args: str) -> subprocess.CompletedProcess:
    return subprocess.run(
        ["git", "-c", "user.email=t@t", "-c", "user.name=t", *args],
        cwd=cwd,
        check=True,
        capture_output=True,
        text=True,
    )


def _git_bytes(cwd: Path, *args: str) -> bytes:
    return subprocess.run(
        ["git", *args],
        cwd=cwd,
        check=True,
        capture_output=True,
    ).stdout


def _managed_repo(tmp_path: Path, files: dict[str, bytes]) -> Path:
    """Create the historical managed-checkout state with autocrlf=true."""
    repo = tmp_path / "managed"
    repo.mkdir(parents=True)
    _git(repo, "init")
    for name, body in files.items():
        path = repo / name
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_bytes(body)
    _git(repo, "-c", "core.autocrlf=false", "add", "-A")
    _git(repo, "commit", "-m", "init")
    _git(repo, "config", "core.autocrlf", "true")
    for name in files:
        (repo / name).unlink()
    _git(repo, "checkout", "--", ".")

    # Force Git to inspect the worktree rather than trusting a racy stat cache.
    import os
    import time

    bumped = time.time() + 5
    for name in files:
        os.utime(repo / name, (bumped, bumped))
    return repo


def _autocrlf(repo: Path) -> str:
    out = subprocess.run(
        ["git", "config", "--local", "--get", "core.autocrlf"],
        cwd=repo,
        capture_output=True,
        text=True,
    )
    return out.stdout.strip()


def _make_local_update_repos(tmp_path: Path) -> tuple[Path, Path]:
    """Create a local checkout plus a local-only origin with one update."""
    origin = tmp_path / "origin.git"
    repo = tmp_path / "checkout"
    upstream = tmp_path / "upstream-work"

    origin.mkdir()
    repo.mkdir()
    _git(origin, "init", "--bare")
    _git(repo, "init", "-b", "main")
    _git(repo, "config", "user.email", "tests@example.invalid")
    _git(repo, "config", "user.name", "Hermes EOL Tests")
    (repo / "tracked.py").write_bytes(b"VALUE = 1\n")
    _git(repo, "add", "tracked.py")
    _git(repo, "commit", "-m", "initial")
    _git(repo, "remote", "add", "origin", str(origin))
    _git(repo, "push", "-u", "origin", "main")

    subprocess.run(
        ["git", "clone", str(origin), str(upstream)],
        check=True,
        capture_output=True,
        text=True,
    )
    _git(upstream, "config", "user.email", "tests@example.invalid")
    _git(upstream, "config", "user.name", "Hermes EOL Tests")
    (upstream / "remote.txt").write_bytes(b"remote update\n")
    _git(upstream, "add", "remote.txt")
    _git(upstream, "commit", "-m", "remote update")
    _git(upstream, "push", "origin", "main")
    return repo, origin


def _patch_ordinary_update_runtime(monkeypatch, repo: Path) -> None:
    """Keep the real Git update seam while disabling unrelated installers."""
    monkeypatch.setattr(hermes_main, "PROJECT_ROOT", repo)
    monkeypatch.setattr(hermes_main, "_is_windows", lambda: False)
    monkeypatch.setattr(hermes_main, "_run_pre_update_backup", lambda _args: None)
    monkeypatch.setattr(hermes_main, "_pause_windows_gateways_for_update", lambda: None)
    monkeypatch.setattr(hermes_main, "_resume_windows_gateways_after_update", lambda _state: None)
    monkeypatch.setattr(
        hermes_main,
        "_get_origin_url",
        lambda _git_cmd, _repo: "https://github.com/NousResearch/hermes-agent.git",
    )
    monkeypatch.setattr(hermes_main, "_resolve_update_branch", lambda _args: "main")
    monkeypatch.setattr(hermes_main, "_clear_bytecode_cache", lambda _root: 0)
    monkeypatch.setattr(hermes_main, "_record_bytecode_fingerprint", lambda: None)
    monkeypatch.setattr(hermes_main, "_reload_updated_runtime_modules", lambda: None)
    monkeypatch.setattr(
        hermes_main,
        "_install_python_dependencies_with_optional_fallback",
        lambda *_args, **_kwargs: None,
    )
    monkeypatch.setattr(hermes_main, "_is_termux_env", lambda _env=None: False)
    monkeypatch.setattr(hermes_main, "_upgrade_pip_before_lazy_refresh", lambda *_a, **_k: None)
    monkeypatch.setattr(hermes_main, "_refresh_active_lazy_features", lambda *_a, **_k: True)
    monkeypatch.setattr(
        hermes_main,
        "_refresh_active_memory_provider_dependencies",
        lambda: None,
    )
    monkeypatch.setattr(hermes_main, "_build_web_ui", lambda _root: None)
    monkeypatch.setattr(hermes_main, "_clear_update_incomplete_marker", lambda: None)
    monkeypatch.setattr(hermes_main, "_clear_lazy_refresh_incomplete_marker", lambda: None)
    monkeypatch.setattr(hermes_main, "_kill_stale_dashboard_processes", lambda **_kwargs: None)
    # The live updater purges cached Hermes modules before restarting the
    # gateway.  Disable that production-only reload boundary here so the
    # hermetic gateway/uv doubles below cannot be replaced by real host code.
    monkeypatch.setattr(hermes_main, "_purge_stale_hermes_modules", lambda: None)

    monkeypatch.setattr("hermes_cli.managed_uv.ensure_uv", lambda **_kwargs: None)
    monkeypatch.setattr("hermes_cli.managed_uv.update_managed_uv", lambda **_kwargs: None)
    monkeypatch.setattr(
        "tools.skills_sync.sync_skills",
        lambda **_kwargs: {"copied": [], "updated": [], "user_modified": [], "cleaned": []},
    )
    monkeypatch.setattr("hermes_cli.profiles.list_profiles", lambda: [])

    monkeypatch.setattr(update_cmd, "_UPDATE_CRITICAL_FILES", ("tracked.py",))
    monkeypatch.setattr(update_cmd, "_validate_critical_modules_import", lambda _root: (True, None, None))
    monkeypatch.setattr(update_cmd, "_invalidate_update_cache", lambda: None)
    monkeypatch.setattr(update_cmd, "_update_node_dependencies", lambda: [])
    monkeypatch.setattr(update_cmd, "_write_update_incomplete_marker", lambda: None)
    monkeypatch.setattr(update_cmd, "_write_lazy_refresh_incomplete_marker", lambda: None)
    monkeypatch.setattr(
        update_cmd, "_finish_dashboard_update_cleanup", lambda *_args, **_kwargs: None
    )

    # Keep the EOL/stash tests hermetic: the update's fleet plan, restart phase,
    # and post-restart version probe must never inspect or touch live services.
    monkeypatch.setattr(
        "hermes_cli.update_inventory.collect_runtime_inventory",
        lambda: SimpleNamespace(runtimes=[], to_dict=lambda: {}),
    )
    monkeypatch.setattr(
        "hermes_cli.update_inventory.record_plan_in_receipt",
        lambda *_args, **_kwargs: None,
    )
    monkeypatch.setattr("hermes_cli.gateway.is_macos", lambda: False)
    monkeypatch.setattr("hermes_cli.gateway.supports_systemd_services", lambda: False)
    monkeypatch.setattr("hermes_cli.gateway.find_gateway_pids", lambda **_kwargs: [])
    monkeypatch.setattr(
        "hermes_cli.gateway.find_profile_gateway_processes",
        lambda **_kwargs: [],
    )
    monkeypatch.setattr("hermes_cli.gateway._get_service_pids", lambda **_kwargs: set())
    monkeypatch.setattr(
        "hermes_cli.update_receipt.collect_fleet_versions",
        lambda **_kwargs: [],
    )
    monkeypatch.setattr(
        "hermes_cli.update_receipt.print_fleet_version_matrix",
        lambda *_args, **_kwargs: False,
    )

    monkeypatch.setattr("hermes_cli.config.load_config", lambda: {})
    monkeypatch.setattr("hermes_cli.config.get_missing_env_vars", lambda required_only=True: [])
    monkeypatch.setattr("hermes_cli.config.get_missing_config_fields", lambda: [])
    monkeypatch.setattr("hermes_cli.config.check_config_version", lambda: (5, 5))
    monkeypatch.setattr(
        "hermes_cli.config.migrate_config",
        lambda **_kwargs: {"env_added": [], "config_added": [], "warnings": []},
    )


def _run_ordinary_update(repo: Path, monkeypatch, *, dirty: bool) -> tuple[list, list, list]:
    _patch_ordinary_update_runtime(monkeypatch, repo)
    tracked = repo / "tracked.py"
    user_bytes = b"VALUE = 1\r\n# intentional CRLF edit\r\n"
    untracked_bytes = b"unrelated\x00bytes\r\n"
    if dirty:
        _git(repo, "config", "core.autocrlf", "false")
        tracked.write_bytes(user_bytes)
        (repo / "unrelated.bin").write_bytes(untracked_bytes)

    events: list[str] = []
    git_calls: list[list[str]] = []
    real_run = update_cmd.subprocess.run

    def recording_run(cmd, *args, **kwargs):
        if isinstance(cmd, (list, tuple)) and cmd and cmd[0] == "git":
            git_calls.append([str(part) for part in cmd])
        return real_run(cmd, *args, **kwargs)

    original_eol = update_cmd._normalize_managed_eol

    def eol_noop(*args, **kwargs):
        events.append("eol")
        return original_eol(*args, **kwargs)

    original_stash = update_cmd._stash_local_changes_if_needed
    original_restore = update_cmd._restore_stashed_changes
    original_post_pull_guard = update_cmd._validate_post_pull_critical_files_syntax

    def stash(*args, **kwargs):
        events.append("stash")
        return original_stash(*args, **kwargs)

    def restore(*args, **kwargs):
        events.append("restore")
        return original_restore(*args, **kwargs)

    def post_pull_guard(*args, **kwargs):
        events.append("post-pull")
        return original_post_pull_guard(*args, **kwargs)

    monkeypatch.setattr(update_cmd.subprocess, "run", recording_run)
    monkeypatch.setattr(update_cmd, "_normalize_managed_eol", eol_noop)
    monkeypatch.setattr(
        update_cmd,
        "_validate_post_pull_critical_files_syntax",
        post_pull_guard,
    )
    monkeypatch.setattr(hermes_main, "_stash_local_changes_if_needed", stash)
    monkeypatch.setattr(hermes_main, "_restore_stashed_changes", restore)

    args = SimpleNamespace(
        release_tag=None,
        branch=None,
        yes=True,
        force=False,
        force_venv=False,
    )
    update_cmd._cmd_update_impl(args, gateway_mode=False)
    return events, git_calls, [user_bytes, untracked_bytes]


def test_normalize_managed_eol_preserves_crlf_worktree_index_and_porcelain_exactly(
    tmp_path: Path,
) -> None:
    repo = _managed_repo(tmp_path, {"a.py": b"x = 1\ny = 2\n"})
    path = repo / "a.py"
    intentional = b"x = 1\r\ny = 2\r\n# intentional\r\n"
    path.write_bytes(intentional)

    before = {
        "worktree": path.read_bytes(),
        "index_diff": _git_bytes(repo, "diff", "--cached", "--binary", "--full-index"),
        "porcelain": _git_bytes(repo, "status", "--porcelain=v1", "-z"),
        "autocrlf": _autocrlf(repo),
    }

    update_cmd._normalize_managed_eol(GIT_CMD, repo)

    assert path.read_bytes() == before["worktree"]
    assert _git_bytes(repo, "diff", "--cached", "--binary", "--full-index") == before["index_diff"]
    assert _git_bytes(repo, "status", "--porcelain=v1", "-z") == before["porcelain"]
    assert _autocrlf(repo) == before["autocrlf"] == "true"


def test_normalize_managed_eol_never_runs_checkout_reset_or_clean(
    tmp_path: Path, monkeypatch: pytest.MonkeyPatch
) -> None:
    calls: list[list[str]] = []

    def fail_if_called(cmd, *args, **kwargs):
        calls.append([str(part) for part in cmd])
        raise AssertionError(f"EOL compatibility hook ran Git: {cmd!r}")

    monkeypatch.setattr(update_cmd.subprocess, "run", fail_if_called)
    update_cmd._normalize_managed_eol(GIT_CMD, tmp_path)

    assert calls == []


def test_ordinary_update_autostash_round_trip_preserves_crlf_and_untracked_exactly(
    tmp_path: Path, monkeypatch: pytest.MonkeyPatch
) -> None:
    repo, _origin = _make_local_update_repos(tmp_path)

    events, git_calls, expected = _run_ordinary_update(repo, monkeypatch, dirty=True)

    assert (repo / "remote.txt").read_bytes() == b"remote update\n"
    assert (repo / "tracked.py").read_bytes() == expected[0]
    assert (repo / "unrelated.bin").read_bytes() == expected[1]
    assert events == ["eol", "stash", "post-pull", "restore"]

    stash_apply = [call for call in git_calls if call[1:3] == ["stash", "apply"]]
    stash_drop = [call for call in git_calls if call[1:3] == ["stash", "drop"]]
    assert len(stash_apply) == 1
    assert len(stash_drop) == 1
    assert _git_bytes(repo, "stash", "list") == b""

    stash_push_index = next(i for i, call in enumerate(git_calls) if call[1:3] == ["stash", "push"])
    mutators = {call[1] for call in git_calls[:stash_push_index] if len(call) > 1}
    assert not (mutators & {"checkout", "reset", "clean"})


def test_ordinary_update_clean_checkout_still_completes_without_autostash(
    tmp_path: Path, monkeypatch: pytest.MonkeyPatch
) -> None:
    repo, _origin = _make_local_update_repos(tmp_path)

    events, git_calls, _expected = _run_ordinary_update(repo, monkeypatch, dirty=False)

    assert (repo / "remote.txt").read_bytes() == b"remote update\n"
    assert events == ["eol", "stash", "post-pull"]
    assert not any(call[1:3] == ["stash", "push"] for call in git_calls)
    assert _git_bytes(repo, "stash", "list") == b""


def test_normalize_managed_eol_leaves_other_autocrlf_modes_and_bytes_untouched(
    tmp_path: Path,
) -> None:
    for mode in ("false", "input"):
        repo = _managed_repo(tmp_path / mode, {"a.py": b"x = 1\n"})
        _git(repo, "config", "core.autocrlf", mode)
        before = (repo / "a.py").read_bytes(), _autocrlf(repo)

        update_cmd._normalize_managed_eol(GIT_CMD, repo)

        assert ((repo / "a.py").read_bytes(), _autocrlf(repo)) == before


def test_non_repo_is_ignored(tmp_path: Path, capsys: pytest.CaptureFixture) -> None:
    update_cmd._normalize_managed_eol(GIT_CMD, tmp_path)
    assert capsys.readouterr().out == ""
